## Introduction to PyTorch

In [ ]:
import torch

### Tensors

In [4]:
# Create first 2D tensor
tensor_2d_a = torch.tensor([[1, 2], [3, 4]])
print(tensor_2d_a)

tensor([[1, 2],
        [3, 4]])


In [6]:
# Create second 2D tensor
tensor_2d_b = torch.tensor([[4, 3], [2, 1]])
print(tensor_2d_b)

tensor([[4, 3],
        [2, 1]])


In [8]:
# Matrix multiplication
result = torch.matmul(tensor_2d_a, tensor_2d_b)
print(result)

tensor([[ 8,  5],
        [20, 13]])


In [11]:
# Transposing the first tensor
transposed_a_transposed = tensor_2d_a.T
print(transposed_a_transposed)

tensor([[1, 3],
        [2, 4]])
