## Introduction to PyTorch
This playbook demonstrates basic PyTorch functionalities.

In [2]:
import torch

### Tensors

In [3]:
# Create first 2D tensor
tensor_2d_a = torch.tensor([[1, 2], [3, 4]])
print(tensor_2d_a)

tensor([[1, 2],
        [3, 4]])


In [4]:
# Create second 2D tensor
tensor_2d_b = torch.tensor([[4, 3], [2, 1]])
print(tensor_2d_b)

tensor([[4, 3],
        [2, 1]])


In [5]:
# Matrix multiplication
result = torch.matmul(tensor_2d_a, tensor_2d_b)
print(result)

tensor([[ 8,  5],
        [20, 13]])


In [6]:
# Transposing the first tensor
transposed_a_transposed = tensor_2d_a.T
print(transposed_a_transposed)

tensor([[1, 3],
        [2, 4]])


In [10]:
# Create a 1-D tensor of evenly spaced values within a given interval
print(torch.arange(start=0, end=4, step=1))
print(torch.arange(4)) # Default start is 0 and step is 1

tensor([0, 1, 2, 3])
tensor([0, 1, 2, 3])


In [14]:
# Creating embeddings
embeddings = torch.nn.Embedding(num_embeddings=6, embedding_dim=4)
print(embeddings.weight)

Parameter containing:
tensor([[-0.9468,  0.7820,  0.1046,  0.1460],
        [-2.0446,  0.8320,  0.1683,  0.1786],
        [ 1.2377, -0.5178, -0.2911,  0.7293],
        [ 1.3638,  0.1009,  1.2301,  0.6402],
        [ 1.4230, -0.4678,  1.4973, -0.0633],
        [ 0.1676,  0.1231,  0.4527,  1.0820]], requires_grad=True)
